@template.layout.page(
content = @`
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2 class="text-center">Welcome to Hexlet</h2>
            </div>
        </div>
    </div>
`,
footer = @`
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center">
                <p>Thanks for visiting, come again soon!</p>
            </div>
        </div>
    </div>
`
)